apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kxf6jsdlx-nodejs 
  janus-idp.io/tekton: kxf6jsdlx-nodejs
  backstage.io/kubernetes-id: kxf6jsdlx-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kxf6jsdlx-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml