apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kxf6jsdlx-nodejs
  janus-idp.io/tekton: kxf6jsdlx-nodejs
  backstage.io/kubernetes-id: kxf6jsdlx-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kxf6jsdlx-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
